services:
  i-notebook-client:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - i-notebook
  i-notebook-server:
    build: ./backend
    ports:
      - 8080:8080
    networks:
      - i-notebook
    depends_on:
      - i-notebook-db
  i-notebook-db:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - i-notebook
    volumes:
      - mongo-data:/data/db
networks:
  i-notebook:
    driver: bridge
volumes:
  mongo-data:
    driver: local